---
title: "Fitness Tracker Trends Analysis"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

[Bellabeat] (<https://bellabeat.com/?)> is a women-centric tech and wellness company which develops wearables and accompanying products that monitor biometric and lifestyle data to help women better understand how their bodies work, and as a result, make healthier lifestyle choices. Together with the Bellabeat app, users are able to gain insights with health data related to their activity, sleep, stress, fitness, heart rate, reproductive health and mindfulness habits. The aim of this project is to analyze how non-Bellabeat consumers use their smart fitness devices. With this information, we are to provide high-level recommendations for how these insights can inform Bellabeat's marketing strategy.

This analysis consists of 6 phase: \*\*Ask, Prepare, Process, Analyze, Share\*\* and \*\*Act\*\*.

## **Ask Phase**

### **1. Business Task**

### **2. Questions for The Analysis**

### **3. Stakeholders**

## **Prepare Phase**

### 1. Data Sources

### 2. Accessibility and The Privacy of Data

### 3. Related Information About The Data

### 4. Data Organization and Verification

### 5. Data Limitations

## **Process Phase**

## **Analysis and Share Phase**

## **Act Phase**
